<Project Sdk="Microsoft.NET.Sdk">

  <!-- Base properties -->
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Private dependencies -->
  <ItemGroup>
    <ProjectReference Include="..\src\VividKernel\DataAccessService\VividKernelDataAccessService.csproj" />
    <ProjectReference Include="..\src\VividKernel\DataAccessServiceInMemory\VividKernelDataAccessServiceInMemory.csproj" />
    <ProjectReference Include="..\src\VividKernel\DataAccessServiceInDatabase\VividKernelDataAccessServiceInDatabase.csproj" />
    <ProjectReference Include="..\src\VividKernel\Service\VividKernelService.csproj" />
    <ProjectReference Include="..\src\VividKernel\ServiceCore\VividKernelServiceCore.csproj" />
  </ItemGroup>

  <!-- Public dependencies -->
  <ItemGroup>
    <PackageReference Include="coverlet.msbuild" Version="6.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest" Version="3.6.4" />
  </ItemGroup>

  <!-- Coverage settings -->
  <PropertyGroup>
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutputFormat>cobertura</CoverletOutputFormat>
    <CoverletOutput>TestResults/coverage.cobertura.xml</CoverletOutput>
    <Exclude>[VividKernelTest]*</Exclude>
  </PropertyGroup>

  <!-- Generate the HTML report after coverage is collected -->
  <Target Name="PostCoverageReport" AfterTargets="GenerateCoverageResult">
    <Exec Command="reportgenerator -reports:TestResults/coverage.cobertura.xml -reportTypes:HtmlInline -targetdir:TestResults/" />
  </Target>

</Project>
