# GNU AFFERO GENERAL PUBLIC LICENSE
# Version 3, 19 November 2007
#
# Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
# Everyone is permitted to copy and distribute verbatim copies
# of this license document, but changing it is not allowed.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: vivid-kernel-pgsql-volume
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/vivid-kernel-pgsql-PersistentVolume
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
