# GNU AFFERO GENERAL PUBLIC LICENSE
# Version 3, 19 November 2007
#
# Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
# Everyone is permitted to copy and distribute verbatim copies
# of this license document, but changing it is not allowed.

apiVersion: v1
kind: Secret
metadata:
  name: vivid-kernel-secret
type: Opaque
data:
  POSTGRES_USER: c2E=                     # base64 for 'sa'
  POSTGRES_PASSWORD: eW91cl9wYXNzd29yZA== # base64 for 'your_password'
