# GNU AFFERO GENERAL PUBLIC LICENSE
# Version 3, 19 November 2007
#
# Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
# Everyone is permitted to copy and distribute verbatim copies
# of this license document, but changing it is not allowed.

apiVersion: v1
kind: Secret
metadata:
  name: vivid-kernel-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlyZWFsbHlzZWNyZXRwYXNzd29yZA== # base64 for 'myreallysecretpassword'
  MYSQL_USER: a2VybmVsRGJVc2Vy                          # base64 for 'kernelDbUser'
  MYSQL_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==              # base64 for 'mysecretpassword'
