@Webservice_HostAddress = http://localhost:5190

POST {{Webservice_HostAddress}}/customer
Content-Type: application/json

{
    "id": "my-id",
    "secret": "my-secret"
}

###

POST {{Webservice_HostAddress}}/customer
Content-Type: application/json

{
    "id": "my-id-2",
    "secret": "my-secret-2"
}

###

POST {{Webservice_HostAddress}}/customer/auto
Content-Type: application/json

###

GET {{Webservice_HostAddress}}/customer/my-id
Accept: application/json

###

GET {{Webservice_HostAddress}}/customer/my-id-2
Accept: application/json

###

GET {{Webservice_HostAddress}}/customer/my-id-unknown
Accept: application/json

###

GET {{Webservice_HostAddress}}/customer
Accept: application/json

###